### PR TITLE
Associations:Private-Events

### PR DESCRIPTION
**Pull request by jebitok-dev**
In this project I:-
- setup new rails app, a new repository, and ReadMe file
- made changes to the MVC for the user, events, and invitations together with the migrations, routes, and db.

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi Sharon!
Great job on this project:clap::clap:.**

**Major highlights**

- The project has a descriptive readme
- The commit messages is also very good.

However, there are changes we need to make in order to get the project working:muscle:.

**To improve**

- [ ] Behavior

- After signing up. When I tried to log in, I get this [error](https://imgur.com/a/FJPnWIx). Kindly fix this bug.

- [ ] Project specific

- the events table has column `creator_id` of type `integer`. Instead, what we currently have is the user_id. Kindly correct this.
- an index for `creator_id` column is added.
- the invitation table has column `event_id` of type `integer`
- an index for `event_id` column is added
- the invitation table has column `user_id` of type `integer`
- an index for `user_id` column is added

Why indices for foreign keys are necessary? In short: Since the foreign key columns will be used often to retrieve related information, it's important to index them (queries on those columns will be faster with indexes).

- [ ] There is no main or master branch in the project repository. If you have renamed it to something else, kindly tell us why. Else rename it back to either main or master.

- [ ] Remove commented out codes in event.rb in model

[Optional]

Invites feature \[EXTRA CREDIT IN ODIN\]
- route under `/event/:event_id/invites/new`
- Join model (Invitation) is required to make sure that attendance is not created without invitation (e.g. `before_create` callback usage) 

Make the above-required changes and when you are ready, request another review
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

**Comment by jebitok-dev** [comment]
For the master branch, I longer have it but will be cautious on the next project.

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello there, great job working on this project so far. However, there is one change I faced when I tried to run your app locally.

- [ ] It seems the page stuck on the sign_in page, when I sign up, it succeeds, but when I sign in, it never worked. Please check your session's functionalities. [Optional Hint]: please try to use your helpers for creating ruby methods for checking the user, log in the user when he signs up, and log out the user as well.
- [ ] In your events table, there are two columns ```user_id``` and ```creator_id```, while we only need the column ```creator_id``` with a references to users table to inform the database that a user who creates an event call that user a creator. Please fix that issue in your migrations.

<hr>

Please make these changes, then ask for another CRR. Good luck and happy coding 👨‍💻💻

**Review by oloomoses — APPROVED** [review]
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**


**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Pull request merged**
